SET XACT_ABORT ON;
SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET QUOTED_IDENTIFIER ON;
SET NUMERIC_ROUNDABORT OFF;
GO

MERGE quality.rooms AS target
USING (VALUES
    (N'M001', N'Auto Centre'),
    (N'M103', N'Auto Centre'),
    (N'E102', N'Bellis Centre'),
    (N'E107', N'Bellis Centre'),
    (N'E107A', N'Bellis Centre'),
    (N'E113', N'Bellis Centre'),
    (N'E114', N'Bellis Centre'),
    (N'E114A', N'Bellis Centre'),
    (N'E114B', N'Bellis Centre'),
    (N'E115', N'Bellis Centre'),
    (N'E115A', N'Bellis Centre'),
    (N'E116', N'Bellis Centre'),
    (N'E116A', N'Bellis Centre'),
    (N'E200', N'Bellis Centre'),
    (N'E201', N'Bellis Centre'),
    (N'E201A', N'Bellis Centre'),
    (N'E202', N'Bellis Centre'),
    (N'E204', N'Bellis Centre'),
    (N'E208', N'Bellis Centre'),
    (N'E211', N'Bellis Centre'),
    (N'E211A', N'Bellis Centre'),
    (N'E213', N'Bellis Centre'),
    (N'E214L', N'Bellis Centre'),
    (N'E214R', N'Bellis Centre'),
    (N'E215', N'Bellis Centre'),
    (N'E216D', N'Bellis Centre'),
    (N'E216E', N'Bellis Centre'),
    (N'E217', N'Bellis Centre'),
    (N'E218', N'Bellis Centre'),
    (N'E219', N'Bellis Centre'),
    (N'E220', N'Bellis Centre'),
    (N'E220A', N'Bellis Centre'),
    (N'E221', N'Bellis Centre'),
    (N'E223', N'Bellis Centre'),
    (N'E225', N'Bellis Centre'),
    (N'E227', N'Bellis Centre'),
    (N'E300', N'Bellis Centre'),
    (N'E301', N'Bellis Centre'),
    (N'E306', N'Bellis Centre'),
    (N'E308', N'Bellis Centre'),
    (N'E309', N'Bellis Centre'),
    (N'E311', N'Bellis Centre'),
    (N'E313', N'Bellis Centre'),
    (N'E315', N'Bellis Centre'),
    (N'E316', N'Bellis Centre'),
    (N'E317', N'Bellis Centre'),
    (N'E317A', N'Bellis Centre'),
    (N'E318', N'Bellis Centre'),
    (N'E319', N'Bellis Centre'),
    (N'E320', N'Bellis Centre'),
    (N'E320A', N'Bellis Centre'),
    (N'E320B', N'Bellis Centre'),
    (N'E324', N'Bellis Centre'),
    (N'E326', N'Bellis Centre'),
    (N'E330', N'Bellis Centre'),
    (N'E332', N'Bellis Centre'),
    (N'F001A', N'Brickwork Centre'),
    (N'F001B', N'Brickwork Centre'),
    (N'F001C', N'Brickwork Centre'),
    (N'F001D', N'Brickwork Centre'),
    (N'F001E', N'Brickwork Centre'),
    (N'F001F', N'Brickwork Centre'),
    (N'F002', N'Brickwork Centre'),
    (N'F003', N'Brickwork Centre'),
    (N'G10', N'Business Centre'),
    (N'G11', N'Business Centre'),
    (N'G12', N'Business Centre'),
    (N'G13', N'Business Centre'),
    (N'G18', N'Business Centre'),
    (N'G20', N'Business Centre'),
    (N'A004', N'Campus Central'),
    (N'A106', N'Campus Central'),
    (N'A205', N'Campus Central'),
    (N'A206', N'Campus Central'),
    (N'A207', N'Campus Central'),
    (N'A208', N'Campus Central'),
    (N'A210', N'Campus Central'),
    (N'A211', N'Campus Central'),
    (N'A212', N'Campus Central'),
    (N'A305', N'Campus Central'),
    (N'A306', N'Campus Central'),
    (N'A307', N'Campus Central'),
    (N'A308', N'Campus Central'),
    (N'A310', N'Campus Central'),
    (N'A311', N'Campus Central'),
    (N'A312', N'Campus Central'),
    (N'A405', N'Campus Central'),
    (N'A406', N'Campus Central'),
    (N'A407', N'Campus Central'),
    (N'A408', N'Campus Central'),
    (N'A410', N'Campus Central'),
    (N'A411', N'Campus Central'),
    (N'A412', N'Campus Central'),
    (N'CZONE', N'Construction Centre'),
    (N'D001', N'Construction Centre'),
    (N'D004', N'Construction Centre'),
    (N'D005', N'Construction Centre'),
    (N'D021', N'Construction Centre'),
    (N'D022', N'Construction Centre'),
    (N'D023', N'Construction Centre'),
    (N'D101', N'Construction Centre'),
    (N'D102', N'Construction Centre'),
    (N'D103', N'Construction Centre'),
    (N'D131', N'Construction Centre'),
    (N'D132', N'Construction Centre'),
    (N'D133', N'Construction Centre'),
    (N'D134', N'Construction Centre'),
    (N'B005', N'Digital & Creative Centre'),
    (N'B006', N'Digital & Creative Centre'),
    (N'B007', N'Digital & Creative Centre'),
    (N'B010', N'Digital & Creative Centre'),
    (N'B016', N'Digital & Creative Centre'),
    (N'B016A', N'Digital & Creative Centre'),
    (N'B024', N'Digital & Creative Centre'),
    (N'B025', N'Digital & Creative Centre'),
    (N'B026', N'Digital & Creative Centre'),
    (N'B101', N'Digital & Creative Centre'),
    (N'B106', N'Digital & Creative Centre'),
    (N'B112', N'Digital & Creative Centre'),
    (N'B113', N'Digital & Creative Centre'),
    (N'B114', N'Digital & Creative Centre'),
    (N'B115', N'Digital & Creative Centre'),
    (N'B201', N'Digital & Creative Centre'),
    (N'B204', N'Digital & Creative Centre'),
    (N'B206', N'Digital & Creative Centre'),
    (N'B212', N'Digital & Creative Centre'),
    (N'B214', N'Digital & Creative Centre'),
    (N'B215', N'Digital & Creative Centre'),
    (N'B301', N'Digital & Creative Centre'),
    (N'B302', N'Digital & Creative Centre'),
    (N'B304', N'Digital & Creative Centre'),
    (N'B312', N'Digital & Creative Centre'),
    (N'B313', N'Digital & Creative Centre'),
    (N'H1', N'Futsal Arena'),
    (N'H2', N'Futsal Arena'),
    (N'C004', N'Hair, Beauty & Travel Centre'),
    (N'C005', N'Hair, Beauty & Travel Centre'),
    (N'C006', N'Hair, Beauty & Travel Centre'),
    (N'C101', N'Hair, Beauty & Travel Centre'),
    (N'C102', N'Hair, Beauty & Travel Centre'),
    (N'C103', N'Hair, Beauty & Travel Centre'),
    (N'C104', N'Hair, Beauty & Travel Centre'),
    (N'C106', N'Hair, Beauty & Travel Centre'),
    (N'C109', N'Hair, Beauty & Travel Centre'),
    (N'C110', N'Hair, Beauty & Travel Centre'),
    (N'C201', N'Hair, Beauty & Travel Centre'),
    (N'C202', N'Hair, Beauty & Travel Centre'),
    (N'C203', N'Hair, Beauty & Travel Centre'),
    (N'C204', N'Hair, Beauty & Travel Centre'),
    (N'C205', N'Hair, Beauty & Travel Centre'),
    (N'C206', N'Hair, Beauty & Travel Centre'),
    (N'C207', N'Hair, Beauty & Travel Centre'),
    (N'C208', N'Hair, Beauty & Travel Centre'),
    (N'C209', N'Hair, Beauty & Travel Centre'),
    (N'C210', N'Hair, Beauty & Travel Centre'),
    (N'C211', N'Hair, Beauty & Travel Centre'),
    (N'C212', N'Hair, Beauty & Travel Centre'),
    (N'C213', N'Hair, Beauty & Travel Centre'),
    (N'C214', N'Hair, Beauty & Travel Centre'),
    (N'P003', N'Health & Life Sciences Centre'),
    (N'P004', N'Health & Life Sciences Centre'),
    (N'P005', N'Health & Life Sciences Centre'),
    (N'P029', N'Health & Life Sciences Centre'),
    (N'P031', N'Health & Life Sciences Centre'),
    (N'P032', N'Health & Life Sciences Centre'),
    (N'P103', N'Health & Life Sciences Centre'),
    (N'P104', N'Health & Life Sciences Centre'),
    (N'P105', N'Health & Life Sciences Centre'),
    (N'P106', N'Health & Life Sciences Centre'),
    (N'P118', N'Health & Life Sciences Centre'),
    (N'P129', N'Health & Life Sciences Centre'),
    (N'P130', N'Health & Life Sciences Centre'),
    (N'P131', N'Health & Life Sciences Centre'),
    (N'P132', N'Health & Life Sciences Centre'),
    (N'P133', N'Health & Life Sciences Centre'),
    (N'P134', N'Health & Life Sciences Centre'),
    (N'P139', N'Health & Life Sciences Centre'),
    (N'P140', N'Health & Life Sciences Centre'),
    (N'P203', N'Health & Life Sciences Centre'),
    (N'P204', N'Health & Life Sciences Centre'),
    (N'P205', N'Health & Life Sciences Centre'),
    (N'P206', N'Health & Life Sciences Centre'),
    (N'P218', N'Health & Life Sciences Centre'),
    (N'P229', N'Health & Life Sciences Centre'),
    (N'P230', N'Health & Life Sciences Centre'),
    (N'P231', N'Health & Life Sciences Centre'),
    (N'P232', N'Health & Life Sciences Centre'),
    (N'P233', N'Health & Life Sciences Centre'),
    (N'P234', N'Health & Life Sciences Centre'),
    (N'P239', N'Health & Life Sciences Centre'),
    (N'P240', N'Health & Life Sciences Centre'),
    (N'X03', N'Poly Tunnels'),
    (N'JT100', N'Student Hub'),
    (N'JT106', N'Student Hub'),
    (N'JT107', N'Student Hub'),
    (N'JT109', N'Student Hub'),
    (N'JT110', N'Student Hub'),
    (N'JT208', N'Student Hub'),
    (N'JT210', N'Student Hub'),
    (N'S3/5', N'University Campus Oldham'),
    (N'S3/9', N'University Campus Oldham'),
    (N'JT', N'Upstairs Student Hub')
) AS source(room_code, building_name)
ON target.room_code = source.room_code
WHEN MATCHED THEN
    UPDATE SET building_name = source.building_name,
               is_active = 1,
               archived_at = NULL,
               updated_at = sysutcdatetime()
WHEN NOT MATCHED THEN
    INSERT (room_code, building_name)
    VALUES (source.room_code, source.building_name);
GO
