using System.Text.RegularExpressions;
using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Packaging;
using S = DocumentFormat.OpenXml.Spreadsheet;
using W = DocumentFormat.OpenXml.Wordprocessing;
using TLQS.Api.Data;
using TLQS.Api.V1;

namespace TLQS.Api.Exports;

public sealed record GeneratedExport(byte[] Content, string ContentType, string FileName);

public sealed class ExcelExportService
{
    public GeneratedExport CreateWorkbook(ExportWorkbookData data)
    {
        using var stream = new MemoryStream();
        using (var document = SpreadsheetDocument.Create(stream, SpreadsheetDocumentType.Workbook, true))
        {
            var workbookPart = document.AddWorkbookPart();
            workbookPart.Workbook = new S.Workbook();
            var styles = workbookPart.AddNewPart<WorkbookStylesPart>();
            styles.Stylesheet = CreateStylesheet();
            styles.Stylesheet.Save();
            var sheets = workbookPart.Workbook.AppendChild(new S.Sheets());
            uint sheetId = 1;

            AddSheet(workbookPart, sheets, CreateInformationSheet(data), sheetId++);
            foreach (var sheet in data.Sheets)
                AddSheet(workbookPart, sheets, sheet, sheetId++);
            workbookPart.Workbook.Save();
        }
        return new GeneratedExport(
            stream.ToArray(),
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            $"{SafeFileName(data.ModuleKey)}-{data.GeneratedAt:yyyy-MM-dd}.xlsx");
    }

    private static ExportSheet CreateInformationSheet(ExportWorkbookData data)
    {
        var rows = new List<IReadOnlyList<string?>>
        {
            new string?[] { "Export area", data.DisplayName },
            new string?[] { "Generated by", data.GeneratedBy },
            new string?[] { "Generated at", data.GeneratedAt.ToString("dd MMM yyyy HH:mm 'UTC'") },
            new string?[] { "Academic year", data.Filter.AcademicYear },
            new string?[] { "Faculty", data.Filter.FacultyCode },
            new string?[] { "Sub-team", data.Filter.TeamCode },
            new string?[] { "From date", data.Filter.FromDate?.ToString("dd MMM yyyy") },
            new string?[] { "To date", data.Filter.ToDate?.ToString("dd MMM yyyy") },
            new string?[] { "Status", data.Filter.Status },
            new string?[] { "Interactive row limit", SqlFoundationDataStore.InteractiveExportRowLimit.ToString() }
        };
        foreach (var sheet in data.Sheets.Where(item => item.WasTruncated))
            rows.Add(new string?[] { $"{sheet.Name} warning", $"Results were limited to {SqlFoundationDataStore.InteractiveExportRowLimit:N0} rows. Narrow the filters and export again." });
        return new ExportSheet("Export Information", ["Property", "Value"], rows, false);
    }

    private static void AddSheet(
        WorkbookPart workbookPart,
        S.Sheets sheets,
        ExportSheet data,
        uint sheetId)
    {
        var worksheetPart = workbookPart.AddNewPart<WorksheetPart>();
        using (var writer = OpenXmlWriter.Create(worksheetPart))
        {
            writer.WriteStartElement(new S.Worksheet());
            writer.WriteElement(new S.SheetViews(
                new S.SheetView(
                    new S.Pane
                    {
                        VerticalSplit = 1D,
                        TopLeftCell = "A2",
                        ActivePane = S.PaneValues.BottomLeft,
                        State = S.PaneStateValues.Frozen
                    })
                { WorkbookViewId = 0U }));
            var columns = new S.Columns();
            for (uint index = 1; index <= data.Columns.Count; index++)
                columns.Append(new S.Column { Min = index, Max = index, Width = index == 1 ? 24D : 20D, CustomWidth = true });
            writer.WriteElement(columns);
            writer.WriteStartElement(new S.SheetData());
            WriteRow(writer, data.Columns.Cast<string?>(), 1U);
            foreach (var row in data.Rows) WriteRow(writer, row, 0U);
            writer.WriteEndElement();
            if (data.Columns.Count > 0)
            {
                writer.WriteElement(new S.AutoFilter
                {
                    Reference = $"A1:{ColumnName(data.Columns.Count)}{data.Rows.Count + 1}"
                });
            }
            writer.WriteEndElement();
        }
        sheets.Append(new S.Sheet
        {
            Id = workbookPart.GetIdOfPart(worksheetPart),
            SheetId = sheetId,
            Name = data.Name
        });
    }

    private static void WriteRow(OpenXmlWriter writer, IEnumerable<string?> values, uint styleIndex)
    {
        writer.WriteStartElement(new S.Row());
        foreach (var value in values)
        {
            var clean = CleanCellText(value);
            writer.WriteElement(new S.Cell
            {
                DataType = S.CellValues.InlineString,
                StyleIndex = styleIndex,
                InlineString = new S.InlineString(new S.Text(clean) { Space = SpaceProcessingModeValues.Preserve })
            });
        }
        writer.WriteEndElement();
    }

    private static S.Stylesheet CreateStylesheet() => new(
        new S.Fonts(
            new S.Font(new S.FontName { Val = "Aptos" }, new S.FontSize { Val = 10D }),
            new S.Font(new S.Bold(), new S.Color { Rgb = "FFFFFFFF" }, new S.FontName { Val = "Aptos" }, new S.FontSize { Val = 10D })),
        new S.Fills(
            new S.Fill(new S.PatternFill { PatternType = S.PatternValues.None }),
            new S.Fill(new S.PatternFill { PatternType = S.PatternValues.Gray125 }),
            new S.Fill(new S.PatternFill(new S.ForegroundColor { Rgb = "FF087F6F" }) { PatternType = S.PatternValues.Solid })),
        new S.Borders(new S.Border()),
        new S.CellStyleFormats(new S.CellFormat()),
        new S.CellFormats(
            new S.CellFormat { FontId = 0U, FillId = 0U, BorderId = 0U },
            new S.CellFormat { FontId = 1U, FillId = 2U, BorderId = 0U, ApplyFont = true, ApplyFill = true,
                Alignment = new S.Alignment { WrapText = true, Vertical = S.VerticalAlignmentValues.Center } }),
        new S.CellStyles(new S.CellStyle { Name = "Normal", FormatId = 0U, BuiltinId = 0U }));

    private static string ColumnName(int number)
    {
        var name = "";
        while (number > 0)
        {
            number--;
            name = (char)('A' + number % 26) + name;
            number /= 26;
        }
        return name;
    }

    private static string CleanCellText(string? value)
    {
        if (string.IsNullOrEmpty(value)) return "";
        var clean = string.Concat(value.Where(character => character is '\t' or '\n' or '\r' || character >= ' '));
        return clean[..Math.Min(clean.Length, 32_767)];
    }

    private static string SafeFileName(string value) =>
        Regex.Replace(value.ToLowerInvariant(), "[^a-z0-9-]+", "-").Trim('-');
}

public sealed class ExportBrandingOptions
{
    public string ProductName { get; set; } = "i-Elevate";
    public string OrganisationName { get; set; } = "Oldham College";
    public string FooterText { get; set; } = "Teaching and Learning Quality System";
    public string LogoPath { get; set; } = "";
}

public sealed class WordExportService(Microsoft.Extensions.Options.IOptions<ExportBrandingOptions> configuredBranding)
{
    private readonly ExportBrandingOptions _branding = configuredBranding.Value;

    public GeneratedExport CreateRecordReport(RecordReportData data)
    {
        using var stream = new MemoryStream();
        using (var document = WordprocessingDocument.Create(stream, WordprocessingDocumentType.Document, true))
        {
            var main = document.AddMainDocumentPart();
            main.Document = new W.Document(new W.Body());
            AddStyles(main);
            AddHeader(main);
            AddFooter(main);
            var body = main.Document.Body!;
            body.Append(Heading(data.Title, 1));
            body.Append(Paragraph($"{Humanize(data.RecordType)} · {data.Status}", "Subtitle"));
            body.Append(DetailsTable([
                ("Staff member", data.StaffName),
                ("Reviewer", data.ReviewerName),
                ("Organisation", data.Organisation),
                ("Record date", data.RecordDate?.ToString("dd MMM yyyy")),
                ("Created by", data.CreatedBy),
                ("Created at", data.CreatedAt.ToString("dd MMM yyyy HH:mm")),
                ("Record ID", data.RecordId.ToString())
            ]));

            foreach (var section in data.Sections)
            {
                var populated = section.Fields.Where(field => !string.IsNullOrWhiteSpace(field.Value)).ToArray();
                if (populated.Length == 0) continue;
                body.Append(Heading(section.Title, 2));
                foreach (var field in populated)
                {
                    body.Append(Paragraph(field.Label, "FieldLabel"));
                    body.Append(Paragraph(field.Value!, "Normal"));
                }
            }

            if (data.Actions.Count > 0)
            {
                body.Append(Heading("Actions", 2));
                body.Append(ActionTable(data.Actions));
            }
            body.Append(new W.SectionProperties(
                new W.PageSize { Width = 11906U, Height = 16838U },
                new W.PageMargin { Top = 1080, Right = 1080U, Bottom = 1080, Left = 1080U, Header = 500U, Footer = 500U }));
            main.Document.Save();
        }
        return new GeneratedExport(
            stream.ToArray(),
            "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            $"{SafeFileName(data.Title)}-{data.RecordDate?.ToString("yyyy-MM-dd") ?? DateTime.UtcNow.ToString("yyyy-MM-dd")}.docx");
    }

    private void AddHeader(MainDocumentPart main)
    {
        var part = main.AddNewPart<HeaderPart>();
        part.Header = new W.Header(
            new W.Paragraph(
                new W.ParagraphProperties(new W.ParagraphStyleId { Val = "Header" }),
                new W.Run(new W.Text(_branding.ProductName)),
                new W.Run(new W.TabChar()),
                new W.Run(new W.Text(_branding.OrganisationName))));
        part.Header.Save();
        main.Document.Body!.Append(new W.SectionProperties(
            new W.HeaderReference { Type = W.HeaderFooterValues.Default, Id = main.GetIdOfPart(part) }));
    }

    private void AddFooter(MainDocumentPart main)
    {
        var part = main.AddNewPart<FooterPart>();
        part.Footer = new W.Footer(
            new W.Paragraph(
                new W.ParagraphProperties(new W.ParagraphStyleId { Val = "Footer" }),
                new W.Run(new W.Text(_branding.FooterText))));
        part.Footer.Save();
        var properties = main.Document.Body!.Elements<W.SectionProperties>().First();
        properties.Append(new W.FooterReference { Type = W.HeaderFooterValues.Default, Id = main.GetIdOfPart(part) });
    }

    private static void AddStyles(MainDocumentPart main)
    {
        var part = main.AddNewPart<StyleDefinitionsPart>();
        part.Styles = new W.Styles(
            Style("Normal", "Normal", 20, "1F2A27"),
            Style("Title", "Title", 36, "153F35", true),
            Style("Heading1", "Heading 1", 32, "153F35", true, 1),
            Style("Heading2", "Heading 2", 25, "087F6F", true, 2),
            Style("Subtitle", "Subtitle", 20, "62706A"),
            Style("FieldLabel", "Field label", 19, "31423C", true),
            Style("Header", "Header", 18, "087F6F", true),
            Style("Footer", "Footer", 16, "62706A"));
        part.Styles.Save();
    }

    private static W.Style Style(string id, string name, int halfPoints, string colour, bool bold = false, int? outline = null)
    {
        var paragraph = new W.ParagraphProperties(new W.SpacingBetweenLines { After = id == "Normal" ? "120" : "180" });
        if (outline.HasValue) paragraph.Append(new W.OutlineLevel { Val = outline.Value - 1 });
        var run = new W.RunProperties(new W.RunFonts { Ascii = "Aptos", HighAnsi = "Aptos" }, new W.FontSize { Val = halfPoints.ToString() }, new W.Color { Val = colour });
        if (bold) run.Append(new W.Bold());
        return new W.Style(paragraph, run)
        {
            Type = W.StyleValues.Paragraph,
            StyleId = id,
            CustomStyle = id is not ("Normal" or "Heading1" or "Heading2")
        }.WithName(name);
    }

    private static W.Paragraph Heading(string value, int level) => Paragraph(value, level == 1 ? "Heading1" : "Heading2");

    private static W.Paragraph Paragraph(string value, string style) => new(
        new W.ParagraphProperties(new W.ParagraphStyleId { Val = style }),
        new W.Run(new W.Text(value) { Space = SpaceProcessingModeValues.Preserve }));

    private static W.Table DetailsTable(IEnumerable<(string Label, string? Value)> values)
    {
        var table = BasicTable();
        foreach (var (label, value) in values.Where(item => !string.IsNullOrWhiteSpace(item.Value)))
            table.Append(new W.TableRow(Cell(label, true), Cell(value!)));
        return table;
    }

    private static W.Table ActionTable(IReadOnlyList<RecordReportAction> actions)
    {
        var table = BasicTable();
        table.Append(new W.TableRow(Cell("Action", true), Cell("Owner", true), Cell("Due date", true), Cell("Status", true)));
        foreach (var action in actions)
            table.Append(new W.TableRow(Cell(action.Action), Cell(action.Owner ?? ""), Cell(action.DueDate?.ToString("dd MMM yyyy") ?? ""), Cell(action.Status)));
        return table;
    }

    private static W.Table BasicTable() => new(
        new W.TableProperties(
            new W.TableWidth { Width = "5000", Type = W.TableWidthUnitValues.Pct },
            new W.TableBorders(
                new W.TopBorder { Val = W.BorderValues.Single, Color = "D8E0DA", Size = 4U },
                new W.BottomBorder { Val = W.BorderValues.Single, Color = "D8E0DA", Size = 4U },
                new W.LeftBorder { Val = W.BorderValues.Single, Color = "D8E0DA", Size = 4U },
                new W.RightBorder { Val = W.BorderValues.Single, Color = "D8E0DA", Size = 4U },
                new W.InsideHorizontalBorder { Val = W.BorderValues.Single, Color = "D8E0DA", Size = 4U },
                new W.InsideVerticalBorder { Val = W.BorderValues.Single, Color = "D8E0DA", Size = 4U })));

    private static W.TableCell Cell(string value, bool bold = false)
    {
        var run = new W.Run(new W.Text(value) { Space = SpaceProcessingModeValues.Preserve });
        if (bold) run.RunProperties = new W.RunProperties(new W.Bold());
        return new W.TableCell(new W.Paragraph(run), new W.TableCellProperties(new W.TableCellMargin(
            new W.TopMargin { Width = "80", Type = W.TableWidthUnitValues.Dxa },
            new W.BottomMargin { Width = "80", Type = W.TableWidthUnitValues.Dxa },
            new W.TableCellLeftMargin { Width = 100, Type = W.TableWidthValues.Dxa },
            new W.TableCellRightMargin { Width = 100, Type = W.TableWidthValues.Dxa })));
    }

    private static string Humanize(string value) => string.Join(' ', value.Split('_', '-', StringSplitOptions.RemoveEmptyEntries).Select(word => char.ToUpperInvariant(word[0]) + word[1..]));
    private static string SafeFileName(string value) => Regex.Replace(value.ToLowerInvariant(), "[^a-z0-9-]+", "-").Trim('-');
}

internal static class WordStyleExtensions
{
    public static W.Style WithName(this W.Style style, string name)
    {
        style.InsertAt(new W.StyleName { Val = name }, 0);
        return style;
    }
}
